[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501

[browser]
gatherUsageStats = false

[global]
developmentMode = false 